# -*- mode: ruby -*-
# vi: set ft=ruby :

GITLAB_DEB = "gitlab-ce_8.4.2-ce.0_amd64.deb"

Vagrant.configure(2) do |config|
  config.vm.box      = "ubuntu/trusty64"
  config.vm.hostname = "gitlab.rc"

  config.vm.network "public_network", mac: "525542590011", ip: "10.0.0.11", netmask: "255.255.0.0", bridge: "en0: Ethernet"


  config.vm.provider "virtualbox" do |vb|
    vb.gui    = false
    vb.memory = "1536"
    vb.cpus   = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "Disabling SSH password auth"
    sudo sed -e 's/PasswordAuthentication\ yes/PasswordAuthentication\ no/' -i /etc/ssh/sshd_config
    sudo service ssh restart

    sudo apt-get update
    sudo apt-get install -y openssh-server
    sudo apt-get install -y postfix
    (
      cd /vagrant
      wget -N https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/trusty/#{GITLAB_DEB}/download
      sudo dpkg -i #{GITLAB_DEB}
    )
    sudo cp /etc/gitlab/gitlab.rb /etc/gitlab/gitlab.rb.orig
    sudo cp /vagrant/gitlab.rb /etc/gitlab/gitlab.rb
    sudo gitlab-ctl reconfigure
    (
      cd /opt/gitlab/embedded/service/gitlab-rails/app/models
      sudo patch < /vagrant/auto_confirm.patch
    )
    (
      # Replace these with your camp's icons.
      cd /opt/gitlab/embedded/service/gitlab-rails/app/assets/images
      sudo cp /vagrant/georgie_icon.png logo-white.png
      sudo co /vagrant/georgie_icon.png logo-black.png
    )
    (
      cd /opt/gitlab/embedded/service/gitlab-rails
      sudo chown -R git public/assets
      gitlab-rake assets:precompile
    )
    sudo gitlab-ctl restart
  SHELL
end
