# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box      = "ubuntu/trusty64"
  config.vm.hostname = "ntp.rc"

  config.vm.network "public_network", mac: "525542590002", ip: "10.0.0.2", netmask: "255.255.0.0", bridge: "en0: Ethernet"


  config.vm.provider "virtualbox" do |vb|
    vb.gui    = false
    vb.memory = "256"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo sed -e 's/PasswordAuthentication\ yes/PasswordAuthentication\ no/' -i /etc/ssh/sshd_config
    sudo service ssh restart

    sudo sed -e 's/\\/archive.ubuntu.com/\\/nz.archive.ubuntu.com/' -i /etc/apt/sources.list
    sudo apt-get update

    sudo apt-get install -y --force-yes ntp
    sudo cp /vagrant/ntp.conf /etc/ntp.conf
    sudo service ntp restart
  SHELL
end
